/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as artixMemeContestSol from "./ArtixMemeContest.sol";
export type { artixMemeContestSol };
import type * as artixNftSol from "./ArtixNFT.sol";
export type { artixNftSol };
import type * as artixRankingSol from "./ArtixRanking.sol";
export type { artixRankingSol };
import type * as proxy from "./proxy";
export type { proxy };
