/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as artixMemeContestSol from "./ArtixMemeContest.sol";
export * as artixNftSol from "./ArtixNFT.sol";
export * as artixRankingSol from "./ArtixRanking.sol";
export * as proxy from "./proxy";
